name: CI/CD pipeline
on:
    push
jobs:
    CI:
        name: Continious Integration
        runs-on: ubuntu-22.04
        steps:
        -   name: Установка репозитория
            uses: actions/checkout@v4
            with:
                repository: Nikilandgelo/inspiration_frontend
        -   name: Установка NodeJS
            uses: actions/setup-node@v4
            with:
                node-version: 22.3.0
        -   name: Установка зависимостей
            run: npm install
        -   name: Проверка JS кода с помощью ESLint
            run: npx eslint "**/*.{js,jsx}"
        -   name: Проверка стилей с помощью StyleLint
            run: npx stylelint "**/*.scss"
