name: CI/CD pipeline
on:
    push
jobs:
    CI_Frontend:
        name: Frontend Continious Integration
        runs-on: ubuntu-22.04
        steps:
        -   name: Установка репозитория
            uses: actions/checkout@v4
            with:
                repository: Nikilandgelo/inspiration_frontend
        -   name: Установка NodeJS
            uses: actions/setup-node@v4.0.3
        -   name: Установка зависимостей
            run: |
                cd frontend
                npm install
        -   name: Проверка JS кода с помощью ESLint
            run: |
                cd frontend
                npx eslint "**/*.js"
        -   name: Проверка стилей с помощью StyleLint
            run: |
                cd frontend
                npx stylelint "**/*.scss"
    CI_Backend:
        name: Backend Continious Integration
        runs-on: ubuntu-22.04
        steps:
        -   name: Установка репозитория
            uses: actions/checkout@v4
            with:
                repository: Nikilandgelo/inspiration_frontend
        -   name: Установка Python
            uses: actions/setup-python@v5.1.1
        -   name: Установка зависимостей
            run: |
                cd mini_backend
                pip install -r requirements.txt
        -   name: Проверка кода на синтаксические ошибки линтером flake8
            run: flake8 . --exclude=venv/
    CD:
        name: Continious Delivery
        runs-on: ubuntu-22.04
        needs:
            - CI_Frontend
            - CI_Backend
        steps:
        -   name: Создание и настройка SSH папки внутри юзера runner
            run: |
                mkdir ~/.ssh
                echo "${{ secrets.PRIVATE_SSH_KEY }}" > ~/.ssh/id_rsa
                chmod 700 ~/.ssh/id_rsa
                ssh-keyscan ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
        -   name: Подключение через SSH, обновление репозитория на сервере
            run: |
                ssh ${{ secrets.NAME_ON_SERVER }}@${{ secrets.SERVER_IP }} << 'COMMANDS'
                cd inspiration_frontend
                git pull remote main
                COMMANDS
